// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3nB6ezeoNm9qUS3mYIA-WXFc939vcAQ4',
    appId: '1:522320705098:web:cafed9510a4be445e118b3',
    messagingSenderId: '522320705098',
    projectId: 'shopsphere-be7f3',
    authDomain: 'shopsphere-be7f3.firebaseapp.com',
    storageBucket: 'shopsphere-be7f3.firebasestorage.app',
    measurementId: 'G-F181ZFBZ7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4sO5QMT0mBqWY_jbE9-kQ77RMST5ccIM',
    appId: '1:522320705098:android:4f307473c01ad0f8e118b3',
    messagingSenderId: '522320705098',
    projectId: 'shopsphere-be7f3',
    storageBucket: 'shopsphere-be7f3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3nB6ezeoNm9qUS3mYIA-WXFc939vcAQ4',
    appId: '1:522320705098:web:3ef75949af4a7c6ae118b3',
    messagingSenderId: '522320705098',
    projectId: 'shopsphere-be7f3',
    authDomain: 'shopsphere-be7f3.firebaseapp.com',
    storageBucket: 'shopsphere-be7f3.firebasestorage.app',
    measurementId: 'G-28PL8GLFMB',
  );
}
